apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sanosdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Tamaño del disco duro virtual para tus datos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sanosdb
  labels:
    app: sanosdb
spec:
  serviceName: "sanosdb-service"
  replicas: 1 # Las bases de datos transaccionales corren en 1 sola réplica principal
  selector:
    matchLabels:
      app: sanosdb
  template:
    metadata:
      labels:
        app: sanosdb
    spec:
      containers:
      - name: postgres-db
        # La imagen se actualizará dinámicamente mediante el pipeline de GitHub Actions
        image: 782424855823.dkr.ecr.us-east-1.amazonaws.com/sanosdb:${IMAGE_TAG}
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: sanosdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sanosdb-service
spec:
  type: ClusterIP # AISLAMIENTO: No expuesto a internet, solo accesible internamente
  selector:
    app: sanosdb
  ports:
    - protocol: TCP
      port: 5432      # Puerto por donde la buscarán tus microservicios
      targetPort: 5432 # Puerto interno del contenedor