apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanosdb
  labels:
    app: sanosdb
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sanosdb
  template:
    metadata:
      labels:
        app: sanosdb
    spec:
      containers:
      - name: postgres-db
        # La imagen se actualizará dinámicamente mediante el pipeline
        image: 782424855823.dkr.ecr.us-east-1.amazonaws.com/sanosysalvosdb:${IMAGE_TAG}
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {} # <--- ALMACENAMIENTO VOLÁTIL Y TEMPORAL
---
apiVersion: v1
kind: Service
metadata:
  name: sanosdb-service
spec:
  type: ClusterIP # Sigue estando seguro y aislado
  selector:
    app: sanosdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432